### ISSUE TITLE
JyNI-C/src/Python/pythonrun.c:1956 isnt' know struct sigaction context ocontext

### ISSUE THREAD

**Issue by scq0123** [Stewori/JyNI#17]
JyNI-C/src/Python/pythonrun.c:1956:19: error: storage size of ‘context’ isn’t known
  struct sigaction context, ocontext;
                   ^
JyNI-C/src/Python/pythonrun.c:1956:28: error: storage size of ‘ocontext’ isn’t known
  struct sigaction context, ocontext;
                            ^
JyNI-C/src/Python/pythonrun.c:1961:10: error: ‘SIG_ERR’ undeclared (first use in this function)
   return SIG_ERR;

**Comment by Stewori** [comment]
@scq0123 ,
please provide the command line you use for building and more information in general. I cannot reproduce this issue. Did you build using the makefile? Maybe some include is missing? Did you install python-dev package?
What system are you on and which compiler are you using? Are you trying to build using an IDE?

**Comment by scq0123** [comment]
system:  centos7  
compiler:  gcc=4.8.5 python=2.75  python-dev has bean installed.
I only run make in the base path of project

**Comment by scq0123** [comment]
@Stewori 
my system: centos7
compiler: gcc=4.8.5 python=2.75 python-dev has bean installed.
I only run make in the base path of project

**Comment by Stewori** [comment]
Alright, looking into `pythonrun.c` I found that a conditional include of `signal.h` was still out-commented. See https://github.com/Stewori/JyNI/commit/1eb490ebfb35094f259a20c68f4ec3fbbc99df90, which should fix it. I currently cannot tell why my system is not affected by this issue, maybe here `HAVE_SIGNAL_H` is false. (But `signal.h` actually exits on my system... probably my `pyconfig.h` is too generic.)
However, please try it with that recent commit applied. I'm curious about results on centos!
And thanks for spotting this issue.

**Comment by scq0123** [comment]
I have make it success, but valgrind needed to be installed,
Otherwise, the following error is displayed
JyNI-C/src/Objects/obmalloc.c:68:31: fatal error: valgrind/valgrind.h: No such file or directory
 #include <valgrind/valgrind.h>

**Comment by Stewori** [comment]
`WITH_VALGRIND` should be undefined if valgrind is not present and I just checked that (at least on my system) `WITH_VALGRIND` is undefined by default. I cannot tell why this is activated on your system, but you can try to customize the makefile for you by adding `-U WITH_VALGRIND` to `CFLAGS` (c.f. https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html)
