### ISSUE TITLE
Name JyNI.jar Mandatory

### ISSUE THREAD

**Issue by Tatsukyo** [Stewori/JyNI#23]
As you said, it's better to create a new issue, 

When u speak about Nexus u probably refer to the phone, but me i refer to Maven and his nexus
(this : http://www.objis.com/formation-java/tutoriel-maven-deploiement-archiva.html)

I can confirm this to you, when u rename the JyNI.jar like Jyni.jar or JyNITEST.jar it doesn't work
I tried many times before contacting you 

JyNI need to be called JyNI.jar but i don't know why 

I've a Netbeans project which can confirm this to you if u want

**Comment by Stewori** [comment]
As I told you: I didn't test renaming the jar. Could you describe how you launch Jython/JyNI, and how you configure the classpath?

**Comment by Tatsukyo** [comment]
I launch Jython/Jyni with this:

java -cp jython.jar;JyNI.jar org.python.util.jython test.py (this works ! obviously JyNI is named JyNI.jar)
i got this: 
```
D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Jar>java -cp jython.jar;JyNI.jar org.python.util.jython test.py
['D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\Jar', 'D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\Jar\\JyNI.jar', 'D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\Jar\\Lib', 'D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\Jar\\jython.jar\\Lib', '__classpath__', '__pyclasspath__/', 'D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\Libraries', 'D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\DLLs']
<module 'numpy' from 'D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Libraries\numpy\__init__$py.class'>
[0 1 2 3 4 5 6]
Coucou <3
```

but when i rename JyNI.jar like JyNII.jar (it doesnt):
java -cp jython.jar;JyNII.jar org.python.util.jython test.py
and i got this:
```
['D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\Jar', 'D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\Jar\\Lib', 'D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\Jar\\jython.jar\\Lib', '__classpath__', '__pyclasspath__/', 'D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\Libraries', 'D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\DLLs']
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    import numpy as NP
  File "D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Libraries\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Libraries\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Libraries\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Libraries\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Libraries\numpy\core\__init__.py", line 42, in <module>
    from . import defchararray as char
  File "D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Libraries\numpy\core\defchararray.py", line 1669, in <module>
    class chararray(ndarray):
TypeError: Error when calling the metaclass bases
    'getset_descriptor' object is not callable
```


test.py is : 
```
import sys
sys.path.append("D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Libraries")
sys.path.append("D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\DLLs")
print sys.path
import numpy as NP
print NP
A= NP.arange(7)
print A
print "Coucou <3"
```

So obviously, JyNI need to be named JyNI.jar and nothing else

**Comment by Stewori** [comment]
Alright. I looked a bit into the code and probably [this line](https://github.com/Stewori/JyNI/blob/master/JyNI-Java/src/JyNI/JyNIInitializer.java#L91) causes the issue.

So, basically the issue is that JyNI.jar must be on classpath *and* on jyhonpath/pythonpath.
For convenience, JyNI looks for a JyNI.jar on classpath and if it encounters one it copies the entry (including location) to jyhonpath/pythonpath. In case of a custom name this routine does not trigger.

Please try to add your custom-named jar manually to jyhonpath/pythonpath *before* the first C-Extension import is attempted.

If this doesn't help, it would be great if you could try to replace "JyNI.jar" with your custom jar-filename in ``JyNIInitializer.java``. Of course we would need a more general solution if this works.
Suggestions?

**Comment by Tatsukyo** [comment]
tried to add JyNI to the python path but got an error too:
`java -cp jython.jar org.python.util.jython test.py`

```
['D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\Jar\\JyNII.jar', 'D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\Jar', 'D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\Jar\\Lib', 'D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\Jar\\jython.jar\\Lib', '__classpath__', '__pyclasspath__/', 'D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\Libraries', 'D:\\Alexis TRAN\\Documents\\NumpyTest\\TestNumpy\\DLLs']
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import numpy as NP
  File "D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Libraries\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Libraries\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Libraries\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Libraries\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Libraries\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name multiarray
```

test.py is:
```
import sys
sys.path.insert(0,"D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Jar\JyNII.jar")
sys.path.append("D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\Libraries")
sys.path.append("D:\Alexis TRAN\Documents\NumpyTest\TestNumpy\DLLs")
print sys.path
import numpy as NP
print NP
A= NP.arange(7)
print A
print "Coucou <3"
```

maybe i'm not doing this correctly i'm not used to python

and about replace "JyNI.jar" with my custom jar will change nothing, the name will be anyway hardcoded

but what about a Regex? 

maybe something like this?: (i'm not used to regex too ...)
`\bJyNI\b.*\b\.jar\b`
the file name still need to start by JyNI and end by .jar but we can add the version behind JyNI
something like JyNI_2.7_alpha.jar which is cool

**Comment by Stewori** [comment]
> and about replace "JyNI.jar" with my custom jar will change nothing, the name will be anyway hardcoded

This is a crucial step to identify if this is really the cause. Of course this is not the solution.

**Comment by Tatsukyo** [comment]
When i try to change the JyNI-Java folder i got an error with the import everything is red so i can't compile to a new jar so maybe i need to import Jython to JyNI? could u explain me how to ?

**Comment by Stewori** [comment]
There are detailed build instructions in the readme. Don't use IDE for building  JyNI, use make. IDEs have too many pifalls. To build only the Java part use ``make JyNI``. (don't forget e.g. ``-f makefile.win64`` for Windows like shown in the readme).
You can use the IDE for viewing and editing; if it complains much about unknown classes, most likely it doesn't have Jython on its classpath. How to add this is IDE specific.

**Comment by Tatsukyo** [comment]
Yeah i got it after 1-2 hours xD

Currently i'm trying to run the makefile ... i need to configure all (javac not found, java not found, etc...)

Why i'm working with 2 harddrives ...

**Comment by Tatsukyo** [comment]
IT WORKS ! 

i changed the:
```
String[] cp = System.getProperty("java.class.path").split(File.pathSeparator);
for (int i = 0; i < cp.length; ++i)
{
	if (cp[i].endsWith("JyNI.jar")) 
        {
		initState.path.add(0, cp[i]);
		//initState.path.add(0, cp[i]+"/lib-tk");
	}
}
```

with:
```
String[] cp = System.getProperty("java.class.path").split(File.pathSeparator);
for (int i = 0; i < cp.length; ++i) 
{
	Pattern p  = Pattern.compile("\\bJyNI\\b.*\\b\\.jar\\b");
	Matcher m = p.matcher(cp[i]);
	if (m.find()) 
        {
		initState.path.add(0, cp[i]);
		//initState.path.add(0, cp[i]+"/lib-tk");
	}
}
```

i tried if it works with a file named TestJyNI.jar and it's works obviously it's the endsWith
so i changed it with a Regex, now it just need to be start with JyNI and end with .jar
So JyNII.jar won't work but JyNI-Alpha_2.5.jar works 

Just what i needed :D Thanks for ur help Stewori i close this issue

**Comment by Stewori** [comment]
(crossposting the message from https://github.com/Stewori/JyNI/pull/24 here for better visibility)

Thanks for your work on this. I think this commit is a good workaround for now (so I'll accept it), but I wouldn't it consider the final solution. What do you think of having an entry for the jar-name to be added to Pythonpath in the manifest/META-INF? Then one would have to adjust the manifest when changing the jar filename, but it would allow for fully freeform names.
JyNI already involves a specialized META-INF entry for Jython initialization: https://github.com/Stewori/JyNI/blob/master/JyNI-Java/META-INF/services/org.python.core.JythonInitializer

**Comment by Stewori** [comment]
Another idea: We could use a technique like [this](https://stackoverflow.com/questions/1983839/determine-which-jar-file-a-class-is-from) to determine which jar file is hosting JyNI.class. Then copy that jarfile to pythonpath.

**Comment by Tatsukyo** [comment]
if we have an entry for the jar-name in the manifest it will be the same problem, in a way it will be hardcoded, this is exactly why i worked on this 

To explain why i refuse this solution, it's because, To get JyNI, i'm using a Maven Central
so the jar imported in my project (JyNI)
become
JyNI-{version}.jar

that's why i'm using a regex

**Comment by Stewori** [comment]
I'm thinking of use cases beyond maven, especially uberjars. Then the jar name can be really anything. I agree, having to edit the manifest is tedious (but definitely better than having the value in Java code).
Currently I think, detecting the hosting jar-file from ``JyNI.class`` like in the linked stackoverflow topic above, is the best way.

**Comment by Tatsukyo** [comment]
Yeah this is done and tested i commit this to you

**Comment by Tatsukyo** [comment]
Cuz of the merge request i close this
