### ISSUE TITLE
Using JyNI with Jython 2.0-final

### ISSUE THREAD

**Issue by lukehutch** [Stewori/JyNI#5]
Hi, is JyNI OK to use with Jython 2.0-final? The final release came out in May, but JyNI says it needs Jython 2.0-b4.

**Comment by lukehutch** [comment]
Just saw the comment on the latest commit about requiring the latest git version of 2.7 -- sorry for the spam!

**Comment by Stewori** [comment]
Never mind. This should actually be clarified much more visibly. I just didn't yet find time to do so. Until recently I was busy with the JVM language summit. There are a bunch of updates for the homepage and readme outstanding.
